### PR TITLE
fix(local-storage): set http headers correctly

### LINKED ISSUE #95: HttpHeaders are not handled
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

I am not seeing HttpHeaders beeing saved or received in cache.

## Expected behavior

HttpHeaders should be serialized as HttpHeaders otherwise a `.get()` wont longer work in interceptors.

## What is the motivation / use case for changing the behavior?

We have request and correlation ids set in backend in response headers that I put into the response body for better access in templates. This is done in an interceptor.

## Environment

<pre><code>
Angular version: 17

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 20  
- Platform:  Mac 

Others:

</code></pre>

### PR DESCRIPTION
**Pull request by muuvmuuv**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #95

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

This also adds single definition of cache key, from perf perspective this makes sense:

<details>
<summary>Open for link</summary>

https://perf.link/#eyJpZCI6IjJnOWF3bmt3MmkzIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXVxuXG5mdW5jdGlvbiBjcmVhdGVLZXkoa2V5KSB7XG4gIHJldHVybiBgc29tZS0ke2tleX1gO1xufSIsInRlc3RzIjpbeyJuYW1lIjoiRG91YmxlIGV4ZWMgdy9vIGRlZmluZSIsImNvZGUiOiJkYXRhLmZvckVhY2goeCA9PiB7XG4gIGNyZWF0ZUtleSh4KVxuICByZXR1cm4gY3JlYXRlS2V5KHgpXG59KSIsInJ1bnMiOls4MDAwLDExMDAwLDEwMDAsMTEwMDAsMTAwMCwxMDAwLDQwMDAsMTAwMCw0MDAwLDIwMDAsOTAwMCw0MDAwLDEwMDAsMjQwMDAsMTkwMDAsMTAwMCw1MDAwLDEwMDAsNzAwMCwxMDAwLDEwMDAsMTYwMDAsMTAwMCw5MDAwLDYwMDAsMjAwMCwxMDAwLDUwMDAsNzAwMCwyMTAwMCwzMDAwLDEwMDAsMjYwMDAsMzAwMCw0MDAwLDYwMDAsNjAwMCwxMDAwMCw5MDAwLDExMDAwLDEwMDAsMjAwMCwyMDAwLDEwMDAsMjQwMDAsMTEwMDAsNzAwMCwxMjAwMCwxMTAwMCw0MDAwLDYwMDAsMTAwMCw2MDAwLDUwMDAsMjEwMDAsMTAwMCwxNDAwMCwxMDAwLDkwMDAsMTIwMDAsMTAwMCwyMTAwMCwxMjAwMCwxMDAwLDEwMDAsNTAwMCwyMDAwMCwxMjAwMCw5MDAwLDEwMDAsMTEwMDAsMjMwMDAsMjAwMCwxODAwMCwxMzAwMCwxMDAwLDEwMDAsOTAwMCwyMDAwMCwxMDAwMCwxOTAwMCwxMjAwMCw3MDAwLDkwMDAsMjAwMCwxMDAwMCwyNTAwMCw3MDAwLDYwMDAsMTIwMDAsNTAwMCwxMDAwLDEwMDAwLDgwMDAsMzAwMCwxMDAwLDIxMDAwLDI2MDAwLDE2MDAwLDEwMDBdLCJvcHMiOjgwNzB9LHsibmFtZSI6IlNpbmdsZSBleGVjIGFuZCBkZWZpbmUiLCJjb2RlIjoiZGF0YS5mb3JFYWNoKHggPT4ge1xuICBjb25zdCBrID0gY3JlYXRlS2V5KHgpXG4gIHJldHVybiBrXG59KSIsInJ1bnMiOlsxMjAwMCwxMDAwMCwyMDAwLDE5MDAwLDEwMDAsMTAwMCw5MDAwLDIwMDAsNzAwMCwzMDAwLDIwMDAwLDYwMDAsMTAwMCw0MjAwMCwzNzAwMCw0NTAwMCw3MDAwLDIwMDAsMTQwMDAsMTAwMCw0MzAwMCwzMjAwMCw0MDAwLDI2MDAwLDExMDAwLDQwMDAsMTAwMCw3MDAwLDEwMDAwLDM5MDAwLDQwMDAsMTAwMCw0NTAwMCw1MDAwLDcwMDAsOTAwMCwxMTAwMCwyMTAwMCwxOTAwMCwxODAwMCwyMDAwLDMwMDAsMjAwMCwyMzAwMCwzODAwMCwyMDAwMCwxOTAwMCwxMzAwMCwyMjAwMCwxMDAwMCwxMTAwMCw0NTAwMCw4MDAwLDQwMDAsNDIwMDAsMjAwMCwxOTAwMCwzNzAwMCwyNjAwMCwyODAwMCwyMDAwLDQxMDAwLDIxMDAwLDEwMDAsMzEwMDAsODAwMCwzNTAwMCwzMjAwMCwxOTAwMCwyMDAwLDE5MDAwLDQwMDAwLDQwMDAsMzAwMDAsMzMwMDAsNDUwMDAsMjEwMDAsMjMwMDAsMzgwMDAsMjUwMDAsMzAwMDAsMjIwMDAsMTUwMDAsMTkwMDAsNDAwMCwxNDAwMCw0NTAwMCwxNTAwMCwxNDAwMCwxNDAwMCwxMjAwMCwxMDAwLDE4MDAwLDcwMDAsMzAwMCwxMDAwLDMzMDAwLDQ1MDAwLDIwMDAwLDQwMDBdLCJvcHMiOjE3MzgwfV0sInVwZGF0ZWQiOiIyMDI0LTAxLTAxVDE1OjI2OjIwLjU1NloifQ%3D%3D

</details>

fixes #95

### CODE REVIEW

**Review by netanel-utila — COMMENTED** [review]
please add a test that verifies the new code

**Comment by muuvmuuv** [comment]
Isn‘t that tested due to my change in the mock? I also noticed that the clearCachePredicate does not have a previous value in the browser when one is in localStorage, any idea why?

**Comment by NetanelBasal** [comment]
You should test that the current headers persists

**Comment by NetanelBasal** [comment]
The build is stuck from some reason. Did you run the tests locally and they pass?

**Comment by muuvmuuv** [comment]
I did yes. I will have a look the next days

**Comment by muuvmuuv** [comment]
Seems to be related to GH Actions configuration and runner uptime https://github.com/ngneat/cashew/actions/runs/7378588007

**Pull request merged**
